name: 编译 Aria2

# 文件更改就编译
# on: push

# 手动运行编译
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检查
        uses: actions/checkout@v2

#       - name: 更新系统
#         run: |
#           sudo apt update && sudo apt full-upgrade -y

      - name: 准备编译环境
        run: |
          sudo apt update && sudo apt full-upgrade -y
          sudo apt install -y \
            g++-9 \
            autoconf \
            automake \
            autotools-dev \
            autopoint \
            libtool \
            pkg-config \
            libssl-dev \
            libc-ares-dev \
            zlib1g-dev \
            libsqlite3-dev \
            libssh2-1-dev \
            libcppunit-dev \
            libgnutls28-dev nettle-dev libgmp-dev libc-ares-dev libxml2-dev \
            libunistring-dev libp11-kit-dev

      - name: 克隆源码
        env: 
          REPO_URL: https://github.com/aria2/aria2
        run: |
          git clone $REPO_URL aria2

      - name: 设置 GCC 编译环境 【使用 GCC 进行编译】
        run: |
          echo 'CC=gcc-9' >> $GITHUB_ENV
          echo 'CXX=g++-9' >> $GITHUB_ENV
#       - name: 设置 clang 编译环境 【使用 Clang 进行编译】
#         run: |
#           echo 'CC=clang' >> $GITHUB_ENV
#           echo 'CXX=clang++' >> $GITHUB_ENV
      - name: 设置 autoreconf
        run: |
          cd aria2
          autoreconf -i
      - name: 设置 Configure 【静态编译】
        run: |
          cd aria2
          ./configure \
            ARIA2_STATIC=yes \
            CPPFLAGS="-fsanitize=address" LDFLAGS="-fsanitize=address"
#       - name: 设置 Configure With guntls 【静态编译】
#         run: |
#           cd aria2
#           ./configure \
#             ARIA2_STATIC=yes \
#             --with-gnutls --without-openssl --without-appletls --without-wintls \
#             CPPFLAGS="-fsanitize=address" LDFLAGS="-fsanitize=address"
#       - name: 设置 Configure With openssl 【静态编译】
#         run: |
#           cd aria2
#           ./configure \
#             ARIA2_STATIC=yes \
#             --with-openssl --without-gnutls --without-appletls --without-wintls \
#             CPPFLAGS="-fsanitize=address" LDFLAGS="-fsanitize=address"
#       - name: 设置 Configure 【静态编译】
#         run: |
#           cd aria2
#           ./configure \
#             ARIA2_STATIC=yes \
#             --with-gnutls --without-openssl --without-appletls --without-wintls \
#             --with-ca-bundle='/etc/ssl/certs/ca-certificates.crt' \
#             CPPFLAGS="-fsanitize=address" LDFLAGS="-fsanitize=address"
#       - name: 设置 Configure 【非静态编译】
#         run: |
#           cd aria2
#           ./configure \
#             --with-gnutls --without-openssl --without-appletls --without-wintls \
#             --with-ca-bundle='/etc/ssl/certs/ca-certificates.crt' \
#             CPPFLAGS="-fsanitize=address" LDFLAGS="-fsanitize=address"

      - name: 开始编译 Aria2
        run: |
          cd aria2
          make
#       - name: 开始编译 Aria2 【安装到系统中】
#         run: |
#           cd aria2
#           make
#           sudo make install

      - name: 开启 SSH 连接
        uses: P3TERX/ssh2actions@main

      - name : 上传二进制文件
        uses: actions/upload-artifact@master
        with:
          name: aria2_binary
          path: /home/runner/work/auto_Compile_aria2/auto_Compile_aria2/aria2/src/aria2c
#           path: /usr/local/bin/aria2c

      - name: 移除旧的编译文件
        uses: c-hive/gha-remove-artifacts@v1.2.0
        with:
          age: '1 day'
          skip-recent: 5

#       - name: 移除旧的 Release 发布
#         uses: dev-drprasad/delete-older-releases@v0.1.0
#         if: env.UPLOAD_RELEASE == 'true' && !cancelled()
#         with:
#           keep_latest: 5
#           delete_tags: true
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
